name: 'Setup jq environment'
description: 'GitHub Action to setup the `jq` command for json parsing'
author: 'urgn'

outputs:
  jq-binary:
    description: 'The pinary path for the jq command'
    value: ${{ steps.install-jq.outputs.jq-binary }}
    
runs:
  using: "composite"
  steps:
    - name: Install jq
      id: install-jq
      shell: bash
      run: |
        mkdir -p ${HOME}/.local/bin
        wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O ${HOME}/.local/bin/jq
        chmod +x ${HOME}/.local/bin/jq
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
        ls -la ${HOME}/.local/bin
        echo "::set-output name=jq-binary::${HOME}/.local/bin/jq"
